// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp5OrSUYde1PAV9zBX7AECF67hBqCcfnM',
    appId: '1:834434905878:web:575f03581cccaeccc68237',
    messagingSenderId: '834434905878',
    projectId: 'chat-app-76cc0',
    authDomain: 'chat-app-76cc0.firebaseapp.com',
    storageBucket: 'chat-app-76cc0.firebasestorage.app',
    measurementId: 'G-EY37KW03RS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvI4vA072C_wFj4ytPUQA7gfLWqtWe2jI',
    appId: '1:834434905878:android:7c65c46da0c0ec28c68237',
    messagingSenderId: '834434905878',
    projectId: 'chat-app-76cc0',
    storageBucket: 'chat-app-76cc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjdbTED-go0gEnZrhfXdFe9Bs3hb8Sln4',
    appId: '1:834434905878:ios:1c56b66c91f55c1fc68237',
    messagingSenderId: '834434905878',
    projectId: 'chat-app-76cc0',
    storageBucket: 'chat-app-76cc0.firebasestorage.app',
    iosBundleId: 'com.example.scholerChatApp',
  );
}
